using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Smart.Table
{
    ///<summary>
    ///this code was generated by tools,do not edit this code
    ///</summary>
    [System.Serializable]
    public class FrameConfigTableItem : ITable
    {
        
        public int getId()
        {
            return ID;
        }
        public int ID;
		public string Name;
		public string[] InitParams;
		public int LoadType;
    }
    //[CreateAssetMenu]
    public class FrameConfigTable : ScriptableObject
    {
        public FrameConfigTableItem[] datas = new FrameConfigTableItem[0];
        protected Dictionary<int,FrameConfigTableItem> table = null;
        public void MakeTable()
        {
            table = new Dictionary<int, FrameConfigTableItem>(datas.Length);
            for(int i = 0 ; i < datas.Length ; ++i)
            {
                table.Add(datas[i].getId(),datas[i]);
            }
        }
        public FrameConfigTableItem GetTableItem(int iId)
        {
            if(null != table && table.ContainsKey(iId))
            {
                return table[iId];
            }
            return null;
        }
    }
}