using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Smart.Table
{
    ///<summary>
    ///this code was generated by tools,do not edit this code
    ///</summary>
    [System.Serializable]
    public class GamePurchaseTableItem : ITable
    {
        
        public int getId()
        {
            return ID;
        }
        public int ID;
		public string Name;
		public int SortID;
		public int IsMain;
		public int NeedPurchaseToUnlock;
		public int[] Attached;
		public string Icon;
		public string Detail;
		public string Desc;
		public string StoreKey;
		public int Price;
    }
    //[CreateAssetMenu]
    public class GamePurchaseTable : ScriptableObject
    {
        public GamePurchaseTableItem[] datas = new GamePurchaseTableItem[0];
        protected Dictionary<int,GamePurchaseTableItem> table = null;
        public void MakeTable()
        {
            table = new Dictionary<int, GamePurchaseTableItem>(datas.Length);
            for(int i = 0 ; i < datas.Length ; ++i)
            {
                table.Add(datas[i].getId(),datas[i]);
            }
        }
        public GamePurchaseTableItem GetTableItem(int iId)
        {
            if(null != table && table.ContainsKey(iId))
            {
                return table[iId];
            }
            return null;
        }
    }
}